<?php

print "<!DOCTYPE html>\n";
print "\n";
print " <html lang=\"en\">\n";
print " <head>\n";
print " <meta charset=\"UTF-8\">\n";
print " <title> Anush's Portfolio</title>\n";
print " <meta name = \"viewpoint\" content = \"width=device-width, user-scalable=no,\n";
print " initial-scale = 1.0, maximum-scale = 1.0, minimum-scale = 1.0\">\n";
print " \n";
print "\n";
print " <!--Font Awesome-->\n";
print "\n";
print "<link rel = \"stylesheet href = \"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
print "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
print "\n";
print "\n";
print "\n";
print " <link rel=\"preload\" href=\"assets/scss/main.scss\" as=\"style\">\n";
print " <link rel=\"preload\" as=\"image\" href=\"assets/images/blogbg.jpeg\">\n";
print "  <link rel=\"preload\" href=\"assets/js/main.js\" as=\"script\">\n";
print "  <link rel=\"preload\" href=\"html/#other-works\" as=\"id\">\n";
print "<link rel=\"preload\" as=\"image\" href=\"assets/images/face3.jpg\">\n";
print "<!--styles-->\n";
print " <link rel =\"stylesheet\" href=\"assets/css/main.css\">\n";
print "\n";
print "\n";
print "\n";
print "\n";
print " <div class = \"header \">\n";
print " 	\n";
print " <div>\n";
print " </head>\n";
print "\n";
print "<body> \n";
print "\n";
print "	<div class=\"header-background \">\n";
print "	<header class = \"header header--sticky \">\n";
print "		\n";
print "		<div class = \"container header__container\">\n";
print "\n";
print "			\n";
print "\n";
print "			<a href=\"index.html\"><img id=\"header-logo\" src=\"assets/images/logo.png\" alt=\"logo\" ></a>\n";
print "			<a href = \"#hero1\" class=\"button header__button\" id = \"header-buttons\"> About</a><br>\n";
print "			<a href = \"#port-title\" class=\"button header__button\" id = \"header-buttons\"> My projects</a><br>\n";
print "\n";
print "			<a href = \"#other-works\" class=\"button  header__button\" id = \"header-buttons\"> Other works</a><br>\n";
print "\n";
print "			<a href = \"https://drive.google.com/file/d/15lDKvoQtnumE4cjRbjmDP0JtaTeI-j90/view?usp=sharing\" class=\"button  header__button\" id = \"header-buttons\">Resume</a><br>\n";
print "			<a href = \"contact.html\" class=\"button  header__button\" id = \"header-buttons\"> Contact Me </a><br>\n";
print "\n";
print "\n";
print "		</div>\n";
print "	</header>\n";
print "\n";
print "		<div id = \"hero1\" class = \"hero\">\n";
print "			<h1 class=\"hero__headline animate-pop-in med--col-5 lrg--col-7\">\n";
print "			Hi, I am Anushervon Rakhmatov;<br>	\n";
print "			a Web Developer based in St. John's, NL.\n";
print "			</h1>\n";
print "			<p class =\"hero__description animate-pop-in med--col-5 lrg--col-7\">I am a fourth year Computer Science student at the Memorial University of Newfoundland. I have a passion for learning new things and love the thrill of solving challenging problems.</p>\n";
print "<p class =\"hero__description animate-pop-in med--col-5 lrg--col-7\">\n";
print "I am knowledgable in object oriented development and Java is my language of choice. I have several Java projects that you can read more about at the Project section of this site. Although I am striving to be a great software developer, I have also had professional experience as a web developer and have practical working knowledge of HTML, CSS and JavaScript. This is a website I created using HTML, CSS, JavaScript, PHP and Photoshop. I enjoy learning about programming, basketball and blockchain technologies.\n";
print "<p>\n";
print "			\n";
print " 		</div>\n";
print " 	</div>\n";
print "\n";
print "<section id = \"portfolio\">\n";
print "\n";
print "	<div class =\"row portfolio\">\n";
print "		<h2 id = \"port-title\" class = \"title-flex\">My projects</h2>\n";
print "\n";
print "		<div class = \"portfolio-piece med--col-4\" style =\"background-image:\n";
print "		url('assets/images/purple.jpg');\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/OurCityFalls-JS-game-\">Our City Falls</h3>\n";
print "		<p class = \"portfolio-piece__tags\">8-bit pixel video game - HTML5,Javascript</p></a>\n";
print "		</div>\n";
print "		\n";
print "\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/green.png')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/afr741.github.io\">Web Portfolio</h3>\n";
print "		<p class = \"portfolio-piece__tags\">HTML5, CSS, Javascript, PHP</p></a>\n";
print "		</div>\n";
print "		\n";
print "		\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/green1.jpg')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/Social_Network_Website\">The Social Network with geolocation</h3>\n";
print "		<p class = \"portfolio-piece__tags\">HTML, CSS, Javascript, Nodejs</p></a>\n";
print "		</div>\n";
print "		\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/blue.png')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/TournamentApp\">TournamentApp</h3>\n";
print "		<p class = \"portfolio-piece__tags\">Java</p></a>\n";
print "		</div>\n";
print "\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/red1.JPG')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/pacman\">Pacman - a classic 8-pixel video game</h3>\n";
print "		<p class = \"portfolio-piece__tags\">HTML5, Javascript</p></a>\n";
print "		</div>\n";
print "		\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/yellow.jpg')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/MIPS-decoder\">MIPS decoder written in Java</h3>\n";
print "		<p class = \"portfolio-piece__tags\">Java</p></a>\n";
print "		</div>\n";
print "\n";
print "		<div class = \"portfolio-piece med--col-4\" style =\"background-image: url('assets/images/teal.jpg');\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"https://github.com/afr741/MySQL-PHP-queries\">PHP queries for the Mysql database</h3>\n";
print "		<p class = \"portfolio-piece__tags\">SQL, PHP</p></a>\n";
print "		</div>\n";
print "\n";
print "		<div class = \"portfolio-piece med--col-4\" style = \"background-image: url('assets/images/orange.png')\">\n";
print "			<h3 class = \"portfolio-piece__title\"><a href= \"\">Reactapp</h3>\n";
print "		<p class = \"portfolio-piece__tags\">HTML5, ReactJS</p></a>\n";
print "		</div>\n";
print "\n";
print "\n";
print "		</section>\n";
print "		\n";
print "			<section id=\"other-works\">\n";
print "			<div class = \"row\">\n";
print "				<div class=\"other-works\">\n";
print "				<h2 class = \"title-flex\">Other works</h2>\n";
print "				<p class =\"hero__description med--col-5 lrg--col-7\">\n";
print "While working as a Digital Media Consultant/Tutor I was involved in development of various graphical content which includes: Logos, Brochures, Infographics, 3D models,magazines, photoshop images, animations, cards, video montages and promotional videos and presentations. Here are some examples of my work:\n";
print "</p>\n";
print "<div class = row other-workslist>\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-helmet.png\">\n";
print "      <img src=\"assets/images/demo-helmet.png\" alt=\"Forest\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">3D model of Daft-Punk helmet designed using AutoDesk Fusion 360</div>\n";
print "  </div>\n";
print "</div>\n";
print "\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-logo.png\">\n";
print "      <img src=\"assets/images/demo-logo.png\" alt=\"Forest\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">A logo designed using Adobe Photoshop</div>\n";
print "  </div>\n";
print "</div>\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"https://www.youtube.com/watch?v=dx2cN7LRv-Q&t=25s\">\n";
print "      <img src=\"assets/images/demo-video.jpg\" alt=\"youtube video\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">A promo video for the Commons at the Queen Elizabeth II Library designed in Adobe Premiere </div>\n";
print "  </div>\n";
print "</div>\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-apple.jpg\">\n";
print "      <img src=\"assets/images/demo-apple.jpg\" alt=\"apple\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">An apple immage created from scratch in photoshop using shapes, masking and color-refining</div>\n";
print "  </div>\n";
print "</div>\n";
print "\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-illustrator.jpg\">\n";
print "      <img src=\"assets/images/demo-illustrator.jpg\" alt=\"Forest\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">A Mandala created in the Adobe Illustrator</div>\n";
print "  </div>\n";
print "</div>\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-photoshop.jpg\">\n";
print "      <img src=\"assets/images/demo-photoshop.jpg\" alt=\"photoshop\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">A dispersion effect added using Adobe Photoshop</div>\n";
print "  </div>\n";
print "</div>\n";
print "\n";
print "<div class=\"responsive\">\n";
print "  <div class=\"gallery\">\n";
print "    <a target=\"_blank\" href=\"assets/images/demo-animation.gif\">\n";
print "      <img src=\"assets/images/demo-animation.gif\" alt=\"animation\" width=\"600\" height=\"400\">\n";
print "    </a>\n";
print "    <div class=\"desc\">Simple animation created in Photoshop</div>\n";
print "  </div>\n";
print "</div>\n";
print "</div>\n";
print "	</div>\n";
print "	 <a href =\"https://eportfolio.mun.ca/afr741\"><p>Check out more in my second portfolio...</p></a>\n";
print "	</section>\n";
print "		\n";
print " 	<section id = \"contact\" class = \"contact\">\n";
print "	<h2 class = \"contact__title white center\">Get in Touch</h2>\n";
print "	<div class = \"contact__social social\">\n";
print "	<a href  = \"https://twitter.com/\" class = \"social__button facebook\"><i class = \"fa fa-facebook\" aria-hidden=\"true\"></i></a>\n";
print "	<a href  = \"https://github.com/afr741\" class = \"social__button github\"><i class = \"fa fa-github\" aria-hidden=\"true\" ></i></a>\n";
print "	<a href  = \"https://www.linkedin.com/in/anushervon-rakhmatov-996026158/\" class = \"social__button linkedin \"><i class = \"fa fa-linkedin\" aria-hidden=\"true\"></i></a>\n";
print "	<a href  = \"https://www.facebook.com/anusher.rahmatov?ref=bookmarks\" class = \"social__button twitter\"><i class = \"fa fa-twitter\" aria-hidden=\"true\"></i></a>\n";
print "	</div>\n";
print "	<a href =\"contact.php\" class = \"button contact__button\" id = \"contact-me\">Contact Me</a>\n";
print "	</section>\n";
print "	\n";
print "	<footer class = \"container\">\n";
print "		<ul class = \"footer-list\">\n";
print "			<li class = \"footer-list__item\"> ©Anushervon Rakhmatov 2018.</li>\n";
print "            <li class=\"footer-list__item\"> All Rights Reserved</li>\n";
print "         </ul>\n";
print "</footer>\n";
print " 	<script src=\"assets/js/main.js\"></script>\n";
print "\n";
print "</body>\n";
print "</html>";

?>
